### ISSUE TITLE
[Info] Projeto agenda existente

### ISSUE THREAD

**Issue by jjaderg** [bahiacoders/agenda_old#5]
Fala galera. A comunidade `FrontendBR` criou um projeto muito bacana justamente sobre uma agenda de eventos voltado ao mundo frontend. Como já discutido em outra issue, ficamos de usar até mesmo o Json e bom, eles fazem isso. Dêem uma olhada:
 - [https://github.com/frontendbr/eventos](https://github.com/frontendbr/eventos)

**Comment by mvfsilva** [comment]
Muito bom @jjaderg, vamos forkar e mandar bala!

**Comment by jjaderg** [comment]
Show boleta. Só olha os commits já feitos, pois acho que estavam criando algo do Firebase (que pode ser usado de com força)

**Comment by mvfsilva** [comment]
Irei analisar, em questão do firebase o @wgbn está no repo, haha!

**Comment by wgbn** [comment]
Particularmente eu entendo porque gostam de complicar tanto pra fazer as coisas. Por que trabalhar com sistema de PR preenchendo JSON hardcoded?
Juro que não consigo entender porque escolhem esse caminho

**Comment by mvfsilva** [comment]
por isso vamos alterar usar firebase no nosso @wgbn

**Comment by jjaderg** [comment]
Justamente, o fork é pra usar uma base ja feita mas modificando e adicionando novas features, no nosso caso o Firebase

**Comment by paulodealmeida** [comment]
Ainda não entendi o que devemos fazer

**Comment by jjaderg** [comment]
@paulodealmeida a ideia é a mesma que discutimos em outra issue. Usar o firebase e popular o front com o json, até pra poder ser usado em outro projeto, como um app mobile por exemplo. A única diferença é que em vez de usar o tema que tinhamos visto, podemos usar agora um muito bem feito e todo customizado por devs brasileiro. Em suma, continuamos na mesma ideia, nada mudou não. Agora é configurar o Firebase pra ser populado com entradas vindas da page, mas acredito que o PR é importante nesse caso por causa do padrao que vai estar o Json

**Comment by paulodealmeida** [comment]
Vamos mudar para o padrão do frontendbr?

**Comment by mvfsilva** [comment]
@paulodealmeida vamos apdatar o frontendbr pra nossa realidade, o escopo continua o mesmo, pois a proposta é a mesma da nossa, apenas estamos aproveitando algo já pronto, para que possamos acelerar o desenvolvimento.

**Comment by paulodealmeida** [comment]
Entendi, me referia aos campos do json, não disse o que era. :tongue:

**Comment by mvfsilva** [comment]
Então galera, posso passar o core pra esse repositório?

**Comment by paulodealmeida** [comment]
pode

**Comment by mvfsilva** [comment]
Projeto migrado para: https://github.com/bahiacoders/agenda
